create type public.jwt_token as (role text, exp integer, sub text);
--
CREATE EXTENSION IF NOT EXISTS pgcrypto;
-- CREATE EXTENSION IF NOT EXISTS postgis;

--
CREATE ROLE super_admin WITH SUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOLOGIN NOREPLICATION BYPASSRLS CONNECTION
LIMIT -1;
GRANT ALL ON SCHEMA public TO super_admin;
GRANT super_admin TO postgres;
--
CREATE ROLE reg_user WITH NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOLOGIN NOREPLICATION NOBYPASSRLS CONNECTION
LIMIT -1;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL ON TABLES TO reg_user;
GRANT ALL ON SCHEMA public TO reg_user;
GRANT reg_user TO postgres;
--
CREATE ROLE anon NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOLOGIN NOREPLICATION NOBYPASSRLS;
GRANT anon TO postgres;
--
GRANT USAGE ON SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO reg_user;
--
GRANT ALL ON TABLE public."User" TO reg_user;
COMMENT ON TABLE "Notification" IS '@mncud';